import test from 'node:test';
import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { Store } from '../src/store.js';
import { Engine } from '../src/engine.js';
import { createMcp } from '../src/server.js';

// The tool schemas are generated by zod-to-json-schema, which answers a reused schema
// instance with a "$ref". Clients that only accept a flat JSON Schema (Gemini, for example)
// answer the whole tools/list request with "Unknown name \"$ref\"" and the model never sees a
// single tool, so every schema instance in src/schema.js is built fresh per use.
test('tools/list describes every tool without $ref', async () => {
  const store = new Store(':memory:');
  const server = createMcp(new Engine(store));
  const client = new Client({ name: 'schema-test', version: '1.0.0' });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  try {
    await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
    const { tools } = await client.listTools();
    const json = JSON.stringify(tools);

    assert.equal(tools.length, 4);
    for (const keyword of ['"$ref"', '"$defs"', '"definitions"']) {
      assert.equal(json.includes(keyword), false, `${keyword} must not reach a client`);
    }

    const query = tools.find(tool => tool.name === 'schedule_query').inputSchema;
    const date = { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}$' };
    const time = { type: 'string', pattern: '^(?:[01]\\d|2[0-3]):[0-5]\\d$' };
    // Reused leaf schemas arrive complete: the date twice, the id both as a field and as items.
    assert.deepEqual(query.properties.from, date);
    assert.deepEqual(query.properties.to, { ...date, description: 'Exclusive end date; default 7 days after from; max 120 days' });
    assert.deepEqual(query.properties.ids, { type: 'array', items: { type: 'string', minLength: 1, maxLength: 160 } });
    assert.deepEqual(query.properties.simulateEnable.items, { type: 'string', minLength: 1, maxLength: 160 });
    assert.deepEqual(query.properties.dayEnd, { ...time, default: '22:00' });

    // ... and the shared id keeps the description of the field it was written on, not of the
    // last place the same instance happened to be serialised.
    assert.equal(query.properties.ids.items.description, undefined);
    assert.ok(query.properties.termId.description.startsWith('Filter courses/events'));
    assert.ok(JSON.stringify(tools.find(tool => tool.name === 'schedule_mutate').inputSchema).includes('effectiveFrom'));
  } finally {
    await client.close();
    await server.close();
    store.close();
  }
});
